// <auto-generated />
using System;
using CinemaBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaBooking.Data.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20190602095347_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaBooking.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SeatId");

                    b.Property<int>("UserId");

                    b.HasKey("BookingId");

                    b.HasIndex("SeatId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Title = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            Title = "Horror"
                        },
                        new
                        {
                            GenreId = 3,
                            Title = "Crime"
                        },
                        new
                        {
                            GenreId = 4,
                            Title = "Drama"
                        },
                        new
                        {
                            GenreId = 5,
                            Title = "Comedy"
                        },
                        new
                        {
                            GenreId = 6,
                            Title = "Adventure"
                        },
                        new
                        {
                            GenreId = 7,
                            Title = "Fantacy"
                        },
                        new
                        {
                            GenreId = 8,
                            Title = "Romance"
                        },
                        new
                        {
                            GenreId = 9,
                            Title = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 10,
                            Title = "Mystrey"
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<decimal>("Ratings");

                    b.Property<string>("Title");

                    b.Property<string>("TrailerUrl");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Description = "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            IsActive = true,
                            Ratings = 9m,
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/watch?v=EXeTwQWrcwY"
                        },
                        new
                        {
                            MovieId = 2,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            IsActive = true,
                            Ratings = 8.8m,
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/watch?v=YoHD9XEInc0"
                        },
                        new
                        {
                            MovieId = 3,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            IsActive = true,
                            Ratings = 9.3m,
                            Title = "The Shawshank Redemption",
                            TrailerUrl = "https://www.youtube.com/watch?v=6hB3S9bIaco"
                        },
                        new
                        {
                            MovieId = 4,
                            Description = "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
                            IsActive = true,
                            Ratings = 8.5m,
                            Title = "The Prestige",
                            TrailerUrl = "https://www.youtube.com/watch?v=ijXruSzfGEc"
                        },
                        new
                        {
                            MovieId = 5,
                            Description = "Maxwell Smart, a highly intellectual but bumbling spy working for the CONTROL agency, is tasked with preventing a terrorist attack from rival spy agency KAOS.",
                            IsActive = true,
                            Ratings = 6.5m,
                            Title = "Get Smart",
                            TrailerUrl = "https://www.youtube.com/watch?v=xbf9AWiJDBI"
                        },
                        new
                        {
                            MovieId = 6,
                            Description = "A young woman suffering from Parkinson's befriends a drug rep working for Pfizer in 1990s Pittsburgh.",
                            IsActive = true,
                            Ratings = 6.7m,
                            Title = "Love & Other Drugs",
                            TrailerUrl = "https://www.youtube.com/watch?v=h6w7Dh-QxzY"
                        },
                        new
                        {
                            MovieId = 7,
                            Description = "Four teenage boys enter a pact to lose their virginity by prom night.",
                            IsActive = true,
                            Ratings = 7m,
                            Title = "American Pie",
                            TrailerUrl = "https://www.youtube.com/watch?v=iUZ3Yxok6N8"
                        },
                        new
                        {
                            MovieId = 8,
                            Description = "A group of friends whose leisurely Mexican holiday takes a turn for the worse when they, along with a fellow tourist, embark on a remote archaeological dig in the jungle where something evil lives among the ruins.",
                            IsActive = true,
                            Ratings = 5.9m,
                            Title = "The Ruins",
                            TrailerUrl = "https://www.youtube.com/watch?v=xVlBRkigRvc"
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.MovieGenre", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("GenreId");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 1,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 9
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 10
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 6
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 8
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 2
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.MovieShowTime", b =>
                {
                    b.Property<int>("MovieId");

                    b.Property<int>("ShowTimeId");

                    b.HasKey("MovieId", "ShowTimeId");

                    b.HasIndex("ShowTimeId");

                    b.ToTable("MovieShowTime");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ShowTimeId = 3
                        },
                        new
                        {
                            MovieId = 1,
                            ShowTimeId = 6
                        },
                        new
                        {
                            MovieId = 1,
                            ShowTimeId = 7
                        },
                        new
                        {
                            MovieId = 1,
                            ShowTimeId = 10
                        },
                        new
                        {
                            MovieId = 1,
                            ShowTimeId = 13
                        },
                        new
                        {
                            MovieId = 1,
                            ShowTimeId = 15
                        },
                        new
                        {
                            MovieId = 2,
                            ShowTimeId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ShowTimeId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            ShowTimeId = 8
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Screen", b =>
                {
                    b.Property<int>("ScreenId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ScreenId");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            ScreenId = 1,
                            Title = "Screen1"
                        },
                        new
                        {
                            ScreenId = 2,
                            Title = "Screen2"
                        },
                        new
                        {
                            ScreenId = 3,
                            Title = "Screen3"
                        },
                        new
                        {
                            ScreenId = 4,
                            Title = "Screen4"
                        },
                        new
                        {
                            ScreenId = 5,
                            Title = "Screen5"
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ScreenId");

                    b.Property<string>("Title");

                    b.HasKey("SeatId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            ScreenId = 1,
                            Title = "A1"
                        },
                        new
                        {
                            SeatId = 2,
                            ScreenId = 1,
                            Title = "A2"
                        },
                        new
                        {
                            SeatId = 3,
                            ScreenId = 1,
                            Title = "A3"
                        },
                        new
                        {
                            SeatId = 4,
                            ScreenId = 1,
                            Title = "A4"
                        },
                        new
                        {
                            SeatId = 5,
                            ScreenId = 1,
                            Title = "A5"
                        },
                        new
                        {
                            SeatId = 6,
                            ScreenId = 1,
                            Title = "A6"
                        },
                        new
                        {
                            SeatId = 7,
                            ScreenId = 1,
                            Title = "A7"
                        },
                        new
                        {
                            SeatId = 8,
                            ScreenId = 1,
                            Title = "A8"
                        },
                        new
                        {
                            SeatId = 9,
                            ScreenId = 1,
                            Title = "A9"
                        },
                        new
                        {
                            SeatId = 10,
                            ScreenId = 1,
                            Title = "A10"
                        },
                        new
                        {
                            SeatId = 11,
                            ScreenId = 1,
                            Title = "B1"
                        },
                        new
                        {
                            SeatId = 12,
                            ScreenId = 1,
                            Title = "B2"
                        },
                        new
                        {
                            SeatId = 13,
                            ScreenId = 1,
                            Title = "B3"
                        },
                        new
                        {
                            SeatId = 14,
                            ScreenId = 1,
                            Title = "B4"
                        },
                        new
                        {
                            SeatId = 15,
                            ScreenId = 1,
                            Title = "B5"
                        },
                        new
                        {
                            SeatId = 16,
                            ScreenId = 1,
                            Title = "B6"
                        },
                        new
                        {
                            SeatId = 17,
                            ScreenId = 1,
                            Title = "B7"
                        },
                        new
                        {
                            SeatId = 18,
                            ScreenId = 1,
                            Title = "B8"
                        },
                        new
                        {
                            SeatId = 19,
                            ScreenId = 1,
                            Title = "B9"
                        },
                        new
                        {
                            SeatId = 20,
                            ScreenId = 1,
                            Title = "B10"
                        },
                        new
                        {
                            SeatId = 21,
                            ScreenId = 1,
                            Title = "C1"
                        },
                        new
                        {
                            SeatId = 22,
                            ScreenId = 1,
                            Title = "C2"
                        },
                        new
                        {
                            SeatId = 23,
                            ScreenId = 1,
                            Title = "C3"
                        },
                        new
                        {
                            SeatId = 24,
                            ScreenId = 1,
                            Title = "C4"
                        },
                        new
                        {
                            SeatId = 25,
                            ScreenId = 1,
                            Title = "C5"
                        },
                        new
                        {
                            SeatId = 26,
                            ScreenId = 1,
                            Title = "C6"
                        },
                        new
                        {
                            SeatId = 27,
                            ScreenId = 1,
                            Title = "C7"
                        },
                        new
                        {
                            SeatId = 28,
                            ScreenId = 1,
                            Title = "C8"
                        },
                        new
                        {
                            SeatId = 29,
                            ScreenId = 1,
                            Title = "C9"
                        },
                        new
                        {
                            SeatId = 30,
                            ScreenId = 1,
                            Title = "C10"
                        },
                        new
                        {
                            SeatId = 31,
                            ScreenId = 2,
                            Title = "A1"
                        },
                        new
                        {
                            SeatId = 32,
                            ScreenId = 2,
                            Title = "A2"
                        },
                        new
                        {
                            SeatId = 33,
                            ScreenId = 2,
                            Title = "A3"
                        },
                        new
                        {
                            SeatId = 34,
                            ScreenId = 2,
                            Title = "A4"
                        },
                        new
                        {
                            SeatId = 35,
                            ScreenId = 2,
                            Title = "A5"
                        },
                        new
                        {
                            SeatId = 36,
                            ScreenId = 2,
                            Title = "A6"
                        },
                        new
                        {
                            SeatId = 37,
                            ScreenId = 2,
                            Title = "A7"
                        },
                        new
                        {
                            SeatId = 38,
                            ScreenId = 2,
                            Title = "A8"
                        },
                        new
                        {
                            SeatId = 39,
                            ScreenId = 2,
                            Title = "B1"
                        },
                        new
                        {
                            SeatId = 40,
                            ScreenId = 2,
                            Title = "B2"
                        },
                        new
                        {
                            SeatId = 41,
                            ScreenId = 2,
                            Title = "B3"
                        },
                        new
                        {
                            SeatId = 42,
                            ScreenId = 2,
                            Title = "B4"
                        },
                        new
                        {
                            SeatId = 43,
                            ScreenId = 2,
                            Title = "B5"
                        },
                        new
                        {
                            SeatId = 44,
                            ScreenId = 2,
                            Title = "B6"
                        },
                        new
                        {
                            SeatId = 45,
                            ScreenId = 2,
                            Title = "B7"
                        },
                        new
                        {
                            SeatId = 46,
                            ScreenId = 2,
                            Title = "B8"
                        },
                        new
                        {
                            SeatId = 47,
                            ScreenId = 3,
                            Title = "A1"
                        },
                        new
                        {
                            SeatId = 48,
                            ScreenId = 3,
                            Title = "A2"
                        },
                        new
                        {
                            SeatId = 49,
                            ScreenId = 3,
                            Title = "A3"
                        },
                        new
                        {
                            SeatId = 50,
                            ScreenId = 3,
                            Title = "A4"
                        },
                        new
                        {
                            SeatId = 51,
                            ScreenId = 3,
                            Title = "A5"
                        },
                        new
                        {
                            SeatId = 52,
                            ScreenId = 3,
                            Title = "A6"
                        },
                        new
                        {
                            SeatId = 53,
                            ScreenId = 3,
                            Title = "A7"
                        },
                        new
                        {
                            SeatId = 54,
                            ScreenId = 3,
                            Title = "A8"
                        },
                        new
                        {
                            SeatId = 55,
                            ScreenId = 3,
                            Title = "B1"
                        },
                        new
                        {
                            SeatId = 56,
                            ScreenId = 3,
                            Title = "B2"
                        },
                        new
                        {
                            SeatId = 57,
                            ScreenId = 3,
                            Title = "B3"
                        },
                        new
                        {
                            SeatId = 58,
                            ScreenId = 3,
                            Title = "B4"
                        },
                        new
                        {
                            SeatId = 59,
                            ScreenId = 3,
                            Title = "B5"
                        },
                        new
                        {
                            SeatId = 60,
                            ScreenId = 3,
                            Title = "B6"
                        },
                        new
                        {
                            SeatId = 61,
                            ScreenId = 3,
                            Title = "B7"
                        },
                        new
                        {
                            SeatId = 62,
                            ScreenId = 3,
                            Title = "B8"
                        },
                        new
                        {
                            SeatId = 63,
                            ScreenId = 3,
                            Title = "C1"
                        },
                        new
                        {
                            SeatId = 64,
                            ScreenId = 3,
                            Title = "C2"
                        },
                        new
                        {
                            SeatId = 65,
                            ScreenId = 3,
                            Title = "C3"
                        },
                        new
                        {
                            SeatId = 66,
                            ScreenId = 3,
                            Title = "C4"
                        },
                        new
                        {
                            SeatId = 67,
                            ScreenId = 3,
                            Title = "C5"
                        },
                        new
                        {
                            SeatId = 68,
                            ScreenId = 3,
                            Title = "C6"
                        },
                        new
                        {
                            SeatId = 69,
                            ScreenId = 3,
                            Title = "C7"
                        },
                        new
                        {
                            SeatId = 70,
                            ScreenId = 3,
                            Title = "C8"
                        },
                        new
                        {
                            SeatId = 71,
                            ScreenId = 4,
                            Title = "A1"
                        },
                        new
                        {
                            SeatId = 72,
                            ScreenId = 4,
                            Title = "A2"
                        },
                        new
                        {
                            SeatId = 73,
                            ScreenId = 4,
                            Title = "A3"
                        },
                        new
                        {
                            SeatId = 74,
                            ScreenId = 4,
                            Title = "A4"
                        },
                        new
                        {
                            SeatId = 75,
                            ScreenId = 4,
                            Title = "A5"
                        },
                        new
                        {
                            SeatId = 76,
                            ScreenId = 4,
                            Title = "A6"
                        },
                        new
                        {
                            SeatId = 77,
                            ScreenId = 4,
                            Title = "A7"
                        },
                        new
                        {
                            SeatId = 78,
                            ScreenId = 4,
                            Title = "A8"
                        },
                        new
                        {
                            SeatId = 79,
                            ScreenId = 4,
                            Title = "A9"
                        },
                        new
                        {
                            SeatId = 80,
                            ScreenId = 4,
                            Title = "A10"
                        },
                        new
                        {
                            SeatId = 81,
                            ScreenId = 4,
                            Title = "B1"
                        },
                        new
                        {
                            SeatId = 82,
                            ScreenId = 4,
                            Title = "B2"
                        },
                        new
                        {
                            SeatId = 83,
                            ScreenId = 4,
                            Title = "B3"
                        },
                        new
                        {
                            SeatId = 84,
                            ScreenId = 4,
                            Title = "B4"
                        },
                        new
                        {
                            SeatId = 85,
                            ScreenId = 4,
                            Title = "B5"
                        },
                        new
                        {
                            SeatId = 86,
                            ScreenId = 4,
                            Title = "B6"
                        },
                        new
                        {
                            SeatId = 87,
                            ScreenId = 4,
                            Title = "B7"
                        },
                        new
                        {
                            SeatId = 88,
                            ScreenId = 4,
                            Title = "B8"
                        },
                        new
                        {
                            SeatId = 89,
                            ScreenId = 4,
                            Title = "B9"
                        },
                        new
                        {
                            SeatId = 90,
                            ScreenId = 4,
                            Title = "B10"
                        },
                        new
                        {
                            SeatId = 91,
                            ScreenId = 4,
                            Title = "C1"
                        },
                        new
                        {
                            SeatId = 92,
                            ScreenId = 4,
                            Title = "C2"
                        },
                        new
                        {
                            SeatId = 93,
                            ScreenId = 4,
                            Title = "C3"
                        },
                        new
                        {
                            SeatId = 94,
                            ScreenId = 4,
                            Title = "C4"
                        },
                        new
                        {
                            SeatId = 95,
                            ScreenId = 4,
                            Title = "C5"
                        },
                        new
                        {
                            SeatId = 96,
                            ScreenId = 4,
                            Title = "C6"
                        },
                        new
                        {
                            SeatId = 97,
                            ScreenId = 4,
                            Title = "C7"
                        },
                        new
                        {
                            SeatId = 98,
                            ScreenId = 4,
                            Title = "C8"
                        },
                        new
                        {
                            SeatId = 99,
                            ScreenId = 4,
                            Title = "C9"
                        },
                        new
                        {
                            SeatId = 100,
                            ScreenId = 4,
                            Title = "C10"
                        },
                        new
                        {
                            SeatId = 101,
                            ScreenId = 4,
                            Title = "D1"
                        },
                        new
                        {
                            SeatId = 102,
                            ScreenId = 4,
                            Title = "D2"
                        },
                        new
                        {
                            SeatId = 103,
                            ScreenId = 4,
                            Title = "D3"
                        },
                        new
                        {
                            SeatId = 104,
                            ScreenId = 4,
                            Title = "D4"
                        },
                        new
                        {
                            SeatId = 105,
                            ScreenId = 4,
                            Title = "D5"
                        },
                        new
                        {
                            SeatId = 106,
                            ScreenId = 4,
                            Title = "D6"
                        },
                        new
                        {
                            SeatId = 107,
                            ScreenId = 4,
                            Title = "D7"
                        },
                        new
                        {
                            SeatId = 108,
                            ScreenId = 4,
                            Title = "D8"
                        },
                        new
                        {
                            SeatId = 109,
                            ScreenId = 4,
                            Title = "D9"
                        },
                        new
                        {
                            SeatId = 110,
                            ScreenId = 4,
                            Title = "D10"
                        },
                        new
                        {
                            SeatId = 111,
                            ScreenId = 4,
                            Title = "E1"
                        },
                        new
                        {
                            SeatId = 112,
                            ScreenId = 4,
                            Title = "E2"
                        },
                        new
                        {
                            SeatId = 113,
                            ScreenId = 4,
                            Title = "E3"
                        },
                        new
                        {
                            SeatId = 114,
                            ScreenId = 4,
                            Title = "E4"
                        },
                        new
                        {
                            SeatId = 115,
                            ScreenId = 4,
                            Title = "E5"
                        },
                        new
                        {
                            SeatId = 116,
                            ScreenId = 4,
                            Title = "E6"
                        },
                        new
                        {
                            SeatId = 117,
                            ScreenId = 4,
                            Title = "E7"
                        },
                        new
                        {
                            SeatId = 118,
                            ScreenId = 4,
                            Title = "E8"
                        },
                        new
                        {
                            SeatId = 119,
                            ScreenId = 4,
                            Title = "E9"
                        },
                        new
                        {
                            SeatId = 120,
                            ScreenId = 4,
                            Title = "E10"
                        },
                        new
                        {
                            SeatId = 121,
                            ScreenId = 5,
                            Title = "B1"
                        },
                        new
                        {
                            SeatId = 122,
                            ScreenId = 5,
                            Title = "B2"
                        },
                        new
                        {
                            SeatId = 123,
                            ScreenId = 5,
                            Title = "B3"
                        },
                        new
                        {
                            SeatId = 124,
                            ScreenId = 5,
                            Title = "B4"
                        },
                        new
                        {
                            SeatId = 125,
                            ScreenId = 5,
                            Title = "B5"
                        },
                        new
                        {
                            SeatId = 126,
                            ScreenId = 5,
                            Title = "B6"
                        },
                        new
                        {
                            SeatId = 127,
                            ScreenId = 5,
                            Title = "B7"
                        },
                        new
                        {
                            SeatId = 128,
                            ScreenId = 5,
                            Title = "B8"
                        },
                        new
                        {
                            SeatId = 129,
                            ScreenId = 5,
                            Title = "B9"
                        },
                        new
                        {
                            SeatId = 130,
                            ScreenId = 5,
                            Title = "B10"
                        },
                        new
                        {
                            SeatId = 131,
                            ScreenId = 5,
                            Title = "C1"
                        },
                        new
                        {
                            SeatId = 132,
                            ScreenId = 5,
                            Title = "C2"
                        },
                        new
                        {
                            SeatId = 133,
                            ScreenId = 5,
                            Title = "C3"
                        },
                        new
                        {
                            SeatId = 134,
                            ScreenId = 5,
                            Title = "C4"
                        },
                        new
                        {
                            SeatId = 135,
                            ScreenId = 5,
                            Title = "C5"
                        },
                        new
                        {
                            SeatId = 136,
                            ScreenId = 5,
                            Title = "C6"
                        },
                        new
                        {
                            SeatId = 137,
                            ScreenId = 5,
                            Title = "C7"
                        },
                        new
                        {
                            SeatId = 138,
                            ScreenId = 5,
                            Title = "C8"
                        },
                        new
                        {
                            SeatId = 139,
                            ScreenId = 5,
                            Title = "C9"
                        },
                        new
                        {
                            SeatId = 140,
                            ScreenId = 5,
                            Title = "C10"
                        },
                        new
                        {
                            SeatId = 141,
                            ScreenId = 5,
                            Title = "D1"
                        },
                        new
                        {
                            SeatId = 142,
                            ScreenId = 5,
                            Title = "D2"
                        },
                        new
                        {
                            SeatId = 143,
                            ScreenId = 5,
                            Title = "D3"
                        },
                        new
                        {
                            SeatId = 144,
                            ScreenId = 5,
                            Title = "D4"
                        },
                        new
                        {
                            SeatId = 145,
                            ScreenId = 5,
                            Title = "D5"
                        },
                        new
                        {
                            SeatId = 146,
                            ScreenId = 5,
                            Title = "D6"
                        },
                        new
                        {
                            SeatId = 147,
                            ScreenId = 5,
                            Title = "D7"
                        },
                        new
                        {
                            SeatId = 148,
                            ScreenId = 5,
                            Title = "D8"
                        },
                        new
                        {
                            SeatId = 149,
                            ScreenId = 5,
                            Title = "D9"
                        },
                        new
                        {
                            SeatId = 150,
                            ScreenId = 5,
                            Title = "D10"
                        },
                        new
                        {
                            SeatId = 151,
                            ScreenId = 5,
                            Title = "E1"
                        },
                        new
                        {
                            SeatId = 152,
                            ScreenId = 5,
                            Title = "E2"
                        },
                        new
                        {
                            SeatId = 153,
                            ScreenId = 5,
                            Title = "E3"
                        },
                        new
                        {
                            SeatId = 154,
                            ScreenId = 5,
                            Title = "E4"
                        },
                        new
                        {
                            SeatId = 155,
                            ScreenId = 5,
                            Title = "E5"
                        },
                        new
                        {
                            SeatId = 156,
                            ScreenId = 5,
                            Title = "E6"
                        },
                        new
                        {
                            SeatId = 157,
                            ScreenId = 5,
                            Title = "E7"
                        },
                        new
                        {
                            SeatId = 158,
                            ScreenId = 5,
                            Title = "E8"
                        },
                        new
                        {
                            SeatId = 159,
                            ScreenId = 5,
                            Title = "E9"
                        },
                        new
                        {
                            SeatId = 160,
                            ScreenId = 5,
                            Title = "E10"
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.ShowTime", b =>
                {
                    b.Property<int>("ShowTimeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ScreenId");

                    b.Property<DateTime>("ShowDateTime");

                    b.HasKey("ShowTimeId");

                    b.HasIndex("ScreenId");

                    b.ToTable("ShowTimes");

                    b.HasData(
                        new
                        {
                            ShowTimeId = 1,
                            ScreenId = 1,
                            ShowDateTime = new DateTime(2019, 5, 27, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 2,
                            ScreenId = 1,
                            ShowDateTime = new DateTime(2019, 5, 27, 17, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 3,
                            ScreenId = 1,
                            ShowDateTime = new DateTime(2019, 5, 27, 20, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 4,
                            ScreenId = 2,
                            ShowDateTime = new DateTime(2019, 5, 27, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 5,
                            ScreenId = 2,
                            ShowDateTime = new DateTime(2019, 5, 27, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 6,
                            ScreenId = 2,
                            ShowDateTime = new DateTime(2019, 5, 27, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 7,
                            ScreenId = 2,
                            ShowDateTime = new DateTime(2019, 5, 27, 23, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 8,
                            ScreenId = 3,
                            ShowDateTime = new DateTime(2019, 5, 27, 13, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 9,
                            ScreenId = 3,
                            ShowDateTime = new DateTime(2019, 5, 27, 15, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 10,
                            ScreenId = 3,
                            ShowDateTime = new DateTime(2019, 5, 27, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 11,
                            ScreenId = 4,
                            ShowDateTime = new DateTime(2019, 5, 27, 15, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 12,
                            ScreenId = 4,
                            ShowDateTime = new DateTime(2019, 5, 27, 19, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 13,
                            ScreenId = 4,
                            ShowDateTime = new DateTime(2019, 5, 27, 22, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 14,
                            ScreenId = 5,
                            ShowDateTime = new DateTime(2019, 5, 27, 14, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 15,
                            ScreenId = 5,
                            ShowDateTime = new DateTime(2019, 5, 27, 18, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowTimeId = 16,
                            ScreenId = 5,
                            ShowDateTime = new DateTime(2019, 5, 27, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Seat", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CinemaBooking.Domain.Entities.AppUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.MovieGenre", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CinemaBooking.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.MovieShowTime", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Movie", "Movie")
                        .WithMany("MovieShowTimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CinemaBooking.Domain.Entities.ShowTime", "ShowTime")
                        .WithMany("MovieShowTimes")
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Seat", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Screen", "Screen")
                        .WithMany("Seats")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.ShowTime", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Screen", "Screen")
                        .WithMany("ShowTimes")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
